### ISSUE TITLE
The new library logs all motor turns as 0 

### ISSUE THREAD

**Issue by KravitzLab** [KravitzLabDevices/FED3#4]
In line 147 numMotorTurns is set to 0 right before logging.  This should be set to 0 after logging?

![image](https://user-images.githubusercontent.com/16770585/106619039-c81dcb80-6535-11eb-802b-1153ae49aad3.png)

**Comment by KravitzLab** [comment]
I think this is fixed now, please check out library v1.2.4.  It should be updatable through the Arduino IDE within the hour or you can download directly here: https://github.com/KravitzLabDevices/FED3_library/releases/tag/v1.2.4

**Comment by matiasandina** [comment]
Yes, this is fixed :)
