### ISSUE TITLE
Behavior of library timeout on free feeding

### ISSUE THREAD

**Issue by matiasandina** [KravitzLabDevices/FED3#5]
From Discussion #2 
`
I think the timeout you noticed may be a "feature" :) I set a default timeout of 10s in the example FreeFeeding script, but you can disable it by removing line 21 (if you don't set a timeout it will default to 0). Can you check if this is the cause of what you're seeing?
`
`
The desired behavior of this program is to drop a pellet, wait until it is removed, start and complete the timeout, and then drop the next pellet. Is that what you're seeing? Rather than respond here do you want to move this to an "issue" so we can keep it straight from your other question?
`
Yes, I am seeing a timeout of 3 seconds on the screen, I configured the 3 seconds timeout thinking it would match the previous 3 seconds delay between pellet deliveries.

I notice the release is slower than before, likely because the timeout period is full timeout, and before it was a simple comparison to see whether 3 seconds had passed? In that sense it would be a strict timeout from pellet removal. Not sure what the previous behavior was.

It results on more noisy pellet delivery than before (I have no data on this, just my eyes and my feeling of "I removed the pellet gimme gimme" while calibrating the devices). I don't think it's going to affect my free feeding task, I just accidentally discovered this by trying to replicate past behavior.

**Comment by KravitzLab** [comment]
Yes I think the prior timeout started at pellet *delivery* and not *removal*.  This wasn't really a timeout, as often by the time the pellet was taken the entire timeout had already elapsed.  I changed this to start the timeout at pellet removal now.  

What do you mean more noisy pellet delivery?  Are you seeing more variance in the time from pellet removal to pellet drop with the new code?  That should be constant except for the variance on how many motor turns it takes to drop a pellet.

**Comment by matiasandina** [comment]
Great, now that is super clear! Do we still have the 3 seconds timeout from delivery? Meaning If I put `timeout = 0`, could I get pellets every 0.5 seconds ?

If I have the lid on, and can't see whether the motor is moving it *feels* different. In principle, this should be as you say, the same as before. But because I effectively need to wait 3 full seconds from removal plus whatever turns, I guess my subjective sensation is different. 

I have also noticed there might be a bit of a longer pause between motor turns or shorter motor turns, is this the case? Before, I had more dual pellet deliveries, not because of failure to detect pellets but because the motor failed to stop before the second pellet was aligned with the chute. I think this is a good thing but it might contribute to the behavior.

**Comment by KravitzLab** [comment]
Yup!  Or you can just remove the line that sets the timeout and timeout will default to 0.  I just tested this and there is still a ~2s delay between removing the pellet and the motor moving to dispense the next one.  This is due to the FED waking up from sleep, writing the SD card, and updating the screen. 

There are ways this could be sped up if needed (inhibit sleep, logging, and updating the screen until later) but it doesn't seem necessary.

**Comment by matiasandina** [comment]
Cool, likely not needed and likely better for overall functioning to have it this way, but good to go under the hood and understand what's there.
